### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by AaronDewes**
This updates multiple dependencies and removes mkdirp, which is now basically built-in in node.

### CODE REVIEW

**Comment by timvisee** [comment]
Very nice work! I'm currently on vacation. Are you okay with me postponing this for next week?

**Comment by AaronDewes** [comment]
> Very nice work! I'm currently on vacation. Are you okay with me postponing this for next week?

Sure!

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
It seems this introduces some styling issues, removing borders.

Before: 
image

After: 
image

Before: 
image

After: 
image

Any idea what is causing this? And, do you mind to fix this?

Other than that, everything looks fantastic.

**Comment by AaronDewes** [comment]
Probably the tailwind update, I will try to fix it.

**Comment by timvisee** [comment]
Fantastic!

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
Thanks a lot once again. I've just merged this!

**Pull request merged**
