### PR TITLE
Added the ability to define a custom footer and URL via environment variables.

### PR DESCRIPTION
**Pull request by HrBingR**
Added the CUSTOM_FOOTER_TEXT and CUSTOM_FOOTER_URL environment variables.

If undefined, the default translated footer will display.

If only CUSTOM_FOOTER_TEXT is defined, only this defined text will display in place of the normal footer text.

If only CUSTOM_FOOTER_URL is defined then the defined URL will display.

If both variables are defined, the defined text will display as a link to the defined URL.

This should resolve issue #88

### CODE REVIEW

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
LGTM. Thanks!

Please let me know if you'd like me to release a new (in between) version with these changes. I'm currently waiting on https://github.com/timvisee/send/pull/102.

**Comment by HrBingR** [comment]
No issues waiting for #102 but are you happy for me to update the docs in the meanwhile, to include the new additions?

**Comment by timvisee** [comment]
> ... but are you happy for me to update the docs in the meanwhile, to include the new additions?

For sure, go ahead!

**Comment by julianq** [comment]
Awesome!!! Excited to update the docker container - thank you!

**Comment by timvisee** [comment]
> Awesome!!! Excited to update the docker container - thank you!

Version `v3.4.21` is releasing now and should be available when this pipeline succeeds: https://gitlab.com/timvisee/send/-/pipelines/630739924

This will also retag the `latest` Docker image.

**Pull request merged**
