### PR TITLE
Remove some polyfills

### PR DESCRIPTION
**Pull request by AaronDewes**
This should reduce the runtime size & load times somewhat by removing polyfills for older browsers which are not used much.
These browsers include the non-chromium Edge and some older versions of Chrome & Firefox.

In addition, it also updates `eslint`

### CODE REVIEW

**Comment by bitfactory-tim-visee** [comment]
Very nice work once again! I glanced through it, and it LGTM.

I'll try to go through this in full and merge this later today.

**Comment by timvisee** [comment]
Very nice work once again! I glanced through it, and it LGTM.

I'll try to go through this in full and merge this later today.

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
This appears to break the crypto check.

This is in Firefox on macOS:

image

image

**Comment by timvisee** [comment]
`crypto.subtle` appears to be missing. I guess a polyfill is required for that.

**Comment by AaronDewes** [comment]
`crypto.subtle` is only available on HTTPS sites and localhost, which is what is causing this. But I'll re-add the polyfill if you develop on other HTTP domains

**Comment by timvisee** [comment]
> `crypto.subtle` is only available on HTTPS sites and localhost, which is what is causing this.

That makes a lot of sense.

**Comment by timvisee** [comment]
I have reverted these changes for the time being (in c624766edc2f14e30eb61d32030d3465bf8ad5fe...4ceac2062361acd254a309348fa38ef15b66e14f) because it is causing issues for users.

Thanks a lot for your work on this though!

I'd be very happy to put this back in once we get https://github.com/timvisee/send/pull/102 resolved.

**Pull request merged**
